name: Test

on: [push, pull_request]

jobs:
  test:
    env:
      GO111MODULE: on
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run verify-gofmt.sh
      run: .github/scripts/verify-gofmt.sh .
    - name: Run go vet
      run: go vet ./...
    # This (and similar install commands) pollute go.mod,
    # which isn't great. We can fix this once we're on
    # go 1.16.x and above by using version suffixes.
    - name: Install golint
      run: go install golang.org/x/lint/golint
    - name: Run golint
      run: .github/scripts/verify-golint.sh ./...
    - name: Install errcheck
      run: go install github.com/kisielk/errcheck
    - name: Run errcheck
      run: errcheck ./...
    - name: Run go install
      run: go install ./...
    - name: Run go test (GOARCH=amd64)
      run: go test ./...
      env:
        GOARCH: amd64
    - name: Run go test (GOARCH=386)
      # darwin/386 isn't supported anymore.
      if: matrix.os != 'macos-latest'
      run: go test ./...
      env:
        GOARCH: 386
